name: CI - TourGuide

on:
  push:
    branches:
    - main
    - dev
  pull_request:
    branches:
    - main
    - dev

jobs:
  build:
    name: deploy to staging
    runs-on: ubuntu-latest

    steps:
    - name: code checkout 
      uses: actions/checkout@v3

    - name: setup .net 7.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: dependency restore
      run: dotnet restore TourGuide.sln

    - name: build
      run: dotnet build TourGuide.sln --configuration Release --no-restore

    - name: tests
      run: dotnet test TourGuide.sln --no-build --verbosity normal

    - name: publish
      run: dotnet publish TourGuide.sln -c Release -o publish

    - name: zip artefact
      run: zip -r TourGuide.zip publish

    - name: artefact upload
      uses: actions/upload-artifact@v4
      with:
        name: TourGuide-zip
        path: TourGuide.zip
